### ISSUE TITLE
Несколько фичереквестов

### ISSUE THREAD

**Issue by XMODER-ua** [rayofhope-dev/dialog-editor#1]
1) Было бы удобно если бы нод с фразой создавался в том месте, где юзер кликнул на add phrase через контекстное меню, а то оно стандартно создается по центру таблицы, и как-то неудобно каждый раз проматывать экран к созданному ноду.
![unknown](https://user-images.githubusercontent.com/26341871/188326737-208d46e2-ecda-4d4e-95ce-259898ebba74.png)

2) Добавить редактирование идентификатора фразы в уже созданном ноде. А то при создании получается можно создать, а отредактировать его уже нельзя.
![unknown2](https://user-images.githubusercontent.com/26341871/188326739-1f2358b2-3fa6-4285-91d3-34fd01e86205.png)

3) В ТЧ немного другая приписка в названии файлов локализации (stable вместо st). Из-за этого если нет файла "st_dialogs_*xxx*", то идёт вылет при сохранении.
Тут можно мб как-то детектить оба файла (и с припиской st и с припиской stable), и если нет обоих вариантов, то пусть программа создаёт этот файл в папке локализации.
![unknown3](https://user-images.githubusercontent.com/26341871/188326904-8f7c3051-6c8e-466f-a460-6d340e8af9de.png)
[roh_dialog_editor.sanya.2022-09-04T20-13-47.log](https://github.com/rayofhope-dev/dialog-editor/files/9485221/roh_dialog_editor.sanya.2022-09-04T20-13-47.log)

**Comment by collectioner** [comment]
@XMODER-ua 
Мы выпустили новую версию, 1.1, в которой эти моменты были учтены, однако, пару заметок по пунктам:
1. мы вроде смогли найти решение по детекту позиции. Но если что-то пойдет не так в момент определения позиции курсора, то нода по дефолту должна отрисоваться в левом верхнем углу, несмотря на скролл и зум всей области;
2. добавлена возможность редактирования `<text>` идентификатора фразы. **P.S.:** изменение идентификатора фразы так же отображается и в файле локализации:
3. в процессе дебага оказалось, что ошибка была при сохранении нового файла (редактор создавал новый, если не находил по шаблону старый). Ошибка исправлена. Вдобавок, добавлена опция настройки формата имени файлов локализации. Формат **должен** иметь "{0}" часть. Она будет заменена на имя файла диалога (вместе с расширением). Т.е.:
Файл локализации для файла диалогов: `dialogs.xml` с форматом имени `prefix_{0}` будет иметь имя:
`prefix_dialogs.xml`

**Comment by collectioner** [comment]
Я закрываю ишую. Если что-то из пунктов будет воспроизводиться, feel free переоткрыть ее заново. Спасибо за фидбек!
