### ISSUE TITLE
Ошибка при открытии сложных диалогов, сделанных раннее вручную 

### ISSUE THREAD

**Issue by UsmanShinobi** [rayofhope-dev/dialog-editor#3]
При открытии сложных диалогов, которые ранее были сделаны вручную (не с помощью оригинального Dialog Editor) ноды располагаются максимально близко друг ко другу, вследствие чего трудно проследить связь между ними. Можно, стоит сделать автоматическое упорядочивание таких диалогов при их открытии (см. следующий багрепорт).

**Comment by collectioner** [comment]
К сожалению, иногда связи бывают слишком комплексные, так что автоматическое упорядочивание/расстановка может быть довольно затруднительной. Ноды возможно передвигать, нажав на ноду и потянув в сторону, поэтому позиции и древо диалога можно выстроить вручную. Вдобавок, редактор поддерживает опцию сохранения позиции фразовых нод (по умолчанию выключена, можно включить через настройки: `Settings -> Save Node Position`. Опционально задается директория для хранения файлов с позициями.)
Так же, есть опция автоматической расстановки (приложение попробует разнести ноды таким образом, чтобы они не пересекались и соблюдалась некая структура).

Мы не планируем реализовывать более "умную" систему расстановки на данный момент, т.к. это потребует значительного времени.

**Comment by UsmanShinobi** [comment]
Да, я уже понял, что лучше самому всё расставить ручками :)

**Comment by collectioner** [comment]
Я закрою этот тикет. Баг с авторасстановкой будем отдельно трекать.
