### ISSUE TITLE
Возможность удалить связь между нодами

### ISSUE THREAD

**Issue by UsmanShinobi** [rayofhope-dev/dialog-editor#6]
Сейчас, похоже нет возможности удалить ошибочно выставленную связь между нодами. Приходится удалять только саму ноду вместе с ошибочной связью

**Comment by collectioner** [comment]
Попробуй правый клик мышкой по зоне с нодами и просто потянуть курсор. Появятся "пунктирные ножницы". Ими можно удалить связь.

**Comment by UsmanShinobi** [comment]
Не знал о такой возможности, как то неочевидно было.

**Comment by collectioner** [comment]
Да, вероятно нам нужен мануал ;)

Проверь, пожалуйста, работает ли эта фича. И если да, то закроем тикет.

**Comment by UsmanShinobi** [comment]
Да, работает, закрою тему)
